# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.6.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/betsalelkogo/ProjectManagement/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: my-cache
          paths:
            - my-cache-file.txt
            - my-project/my-dependencies-directory
  linter:
    executor: my-custom-executor
    steps:
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - checkout
      - run: npm run lint
  test1:
    executor: my-custom-executor
    steps:
      - checkout
      - run: npm run test

workflows:
  my-custom-workflow:
    jobs:
      - build
      - test1:
          requires:
            - build
      - linter:
          requires:
            - build