version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/betsalelkogo/ProjectManagement/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  linter:
    executor: my-custom-executor
    steps:
      - checkout
      - run: npm run lint
      # echo Lint, completed!

workflows:
  my-custom-workflow:
    jobs:
      - linter